version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_HOST
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"
    networks:
      - default
  web:
    image: ntheile/pleb-pool-ui:latest
    user: "0:0"
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ./config:/etc/caddy:rw
    networks:
      - default

networks:
  default:
    name: umbrel_main_network
    external: true
    