version: "3.7"

services:
  app_proxy:
    environment:
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"
  web:
    image: ntheile/pleb-pool-ui:latest@sha256:617a21b49d0816ce8a33aed65a68a5977845f7ad92622a7695e028143d643b7c
    user: "0:0"
    init: true
    volumes:
      - ./config:/etc/caddy:rw